### ISSUE TITLE
More instructions needed

### ISSUE THREAD

**Issue by kevev** [logicent/frontdesk#1]
Hello. I am attempting to use Frontdesk but am stuck at setup.

php oil refine migrate --packages=auth

This command hangs with no logs being generated and no output. I was able to have errors show that I needed to create the DB first. I have done this. But now when running the command nothing happens. Any help would be appreciated.  :)

**Comment by mwaigichuhi** [comment]
> Hello. I am attempting to use Frontdesk but am stuck at setup.
> 
> php oil refine migrate --packages=auth
> 
> This command hangs with no logs being generated and no output. I was able to have errors show that I needed to create the DB first. I have done this. But now when running the command nothing happens. Any help would be appreciated. :)

Hey @kevev I have since re-worked previous projects using the Yii framework since not much support is available with fuelphp so check out the first such release here https://github.com/mwaigichuhi/ajabu-pos
