### ISSUE TITLE
Does it work with apache?

### ISSUE THREAD

**Issue by ugintl** [logicent/frontdesk#2]
Is only nginx supported?

**Comment by mwaigichuhi** [comment]
Nginx is tested/preferred, but you could try using other web servers.

**Comment by ugintl** [comment]
@mwaigichuhi Is fuel php dead? I see there is no development on fuel php and people are not interested anymore.

**Comment by mwaigichuhi** [comment]
There has has not been any active development for a long time now. The projects I released on it were based on work done a while back. I will soon be releasing the updated versions based built on the Yii framework here https://github.com/mwaigichuhi

**Comment by ugintl** [comment]
@mwaigichuhi great

**Comment by mwaigichuhi** [comment]
> @mwaigichuhi great

Hey, check out the first release of previous apps I built here ... https://github.com/mwaigichuhi/ajabu-pos
